version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    # ports:
    #   - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://admin:password@db:27017/?authSource=admin
      - PORT=8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db

  cache:
    image: redis

volumes:
  mongo-db:
